
--A query analisa o faturamento e participação nas vendas  por produto e sabor, assim como a variação anual das vendas por produto.
--Em seguida, classifica se cada produto vendeu acima ou abaixo da média mensal de faturamento.

WITH TABELA_B AS(
SELECT
        DISTINCT P.[NOME_DO_PRODUTO],
        P.SABOR,
        YEAR(NF.DATA_VENDA) AS ANO,
        ROUND(SUM(SUM([quantidade] * [preco])) OVER (PARTITION BY P.[NOME_DO_PRODUTO], YEAR(NF.DATA_VENDA)),2) FATURAMENTO_POR_PRODUTO,
        ROUND(SUM(SUM([quantidade] * [preco])) OVER (PARTITION BY P.[NOME_DO_PRODUTO], YEAR(NF.DATA_VENDA)) /
        SUM(SUM([quantidade] * [preco])) OVER (PARTITION BY  YEAR(NF.DATA_VENDA)),2)*100 SHARE_ANUAL_POR_PRODUTO,
        ROUND(SUM(SUM([quantidade] * [preco])) OVER (PARTITION BY P.[SABOR], YEAR(NF.DATA_VENDA)),2) FATURAMENTO_ANUAL_POR_SABOR,
        ROUND(SUM(SUM([quantidade] * [preco])) OVER (PARTITION BY P.[SABOR],YEAR(NF.DATA_VENDA)) /
        SUM(SUM([quantidade] * [preco])) OVER (PARTITION BY  YEAR(NF.DATA_VENDA)),2)*100 SHARE_SABOR_FATURAMENTO_ANUAL
    FROM 
        [SUCOS_FRUTAS].[dbo].[ITENS_NOTAS_FISCAIS] INF
    LEFT JOIN 
        [SUCOS_FRUTAS].[dbo].[NOTAS_FISCAIS] NF ON INF.NUMERO = NF.NUMERO
    LEFT JOIN 
        [SUCOS_FRUTAS].[dbo].[TABELA_DE_PRODUTOS] P ON INF.[CODIGO_DO_PRODUTO] = P.[CODIGO_DO_PRODUTO]
    WHERE YEAR(NF.DATA_VENDA) IN (2015,2016,2017)
    GROUP BY 
        P.[NOME_DO_PRODUTO], P.SABOR, YEAR(NF.DATA_VENDA)
)

SELECT 
    *,
    ROUND(((FATURAMENTO_POR_PRODUTO - LAG(FATURAMENTO_POR_PRODUTO) OVER (PARTITION BY NOME_DO_PRODUTO ORDER BY ANO)) /
    LAG(FATURAMENTO_POR_PRODUTO) OVER (PARTITION BY NOME_DO_PRODUTO ORDER BY ANO)),2)*100 AS VARIACAO_ANUAL_PRODUTO,
    CASE 
        WHEN FATURAMENTO_POR_PRODUTO >= (
            SELECT AVG(FATURAMENTO_POR_PRODUTO) 
            FROM TABELA_B AS T 
            WHERE T.ANO = TABELA_B.ANO
        ) THEN 'PRODUTO VENDEU ACIMA DA MÉDIA MENSAL'
        ELSE 'PRODUTO VENDEU ABAIXO DA MÉDIA MENSAL' 
    END AS STATUS
FROM 
    TABELA_B
ORDER BY ANO;


--Extrair o TOP Vendendedor Anual do período anual de 2016 e 2017, assim como o valor do comissionamento.

SELECT * FROM (
	 SELECT 
    YEAR(NF.DATA_VENDA) AS ANO, 
    V.NOME,
    ROUND(SUM([quantidade] * [preco]),2) AS FATURAMENTO_ANUAL,
    ROUND((SUM([quantidade] * [preco])) * V.PERCENTUAL_COMISSAO,2) AS COMISSAO_ANUAL,
	RANK()OVER (PARTITION BY YEAR(NF.DATA_VENDA) ORDER BY SUM([quantidade] * [preco]) DESC) AS RANK_VENDAS
FROM 
    [SUCOS_FRUTAS].[dbo].[ITENS_NOTAS_FISCAIS] INF
LEFT JOIN 
    [SUCOS_FRUTAS].[dbo].[NOTAS_FISCAIS] NF ON INF.NUMERO = NF.NUMERO
LEFT JOIN 
    [SUCOS_FRUTAS].[dbo].[TABELA_DE_VENDEDORES] V ON NF.MATRICULA = V.MATRICULA
WHERE YEAR(NF.DATA_VENDA) IN (2016,2017)
GROUP BY 
    YEAR(NF.DATA_VENDA), V.NOME, V.PERCENTUAL_COMISSAO ) AS SUB
	WHERE RANK_VENDAS = 1


----- Análise de vendas por tipo de embalagem e tamanho.

	 SELECT 
    YEAR(NF.DATA_VENDA) AS ANO, 
    P.EMBALAGEM,
	P.TAMANHO,
    ROUND(SUM([quantidade] * [preco]),2) AS FATURAMENTO_ANUAL,
	ROUND(AVG(P.PRECO_DE_LISTA),2) AS PREÇO_MEDIO
FROM 
    [SUCOS_FRUTAS].[dbo].[ITENS_NOTAS_FISCAIS] INF
LEFT JOIN 
    [SUCOS_FRUTAS].[dbo].[NOTAS_FISCAIS] NF ON INF.NUMERO = NF.NUMERO
LEFT JOIN 
    [SUCOS_FRUTAS].[dbo].[TABELA_DE_PRODUTOS] P ON INF.CODIGO_DO_PRODUTO = P.CODIGO_DO_PRODUTO
WHERE YEAR(NF.DATA_VENDA) IN (2016,2017)
GROUP BY YEAR(NF.DATA_VENDA), P.EMBALAGEM,	P.TAMANHO
ORDER BY ANO ASC, FATURAMENTO_ANUAL DESC;


--A query analisa o faturamento e as unidades vendidas mensalmente ao longo de três anos (2015, 2016, 2017),
--calculando a variação mensal em relação ao mês anterior para ambas as métricas.


WITH ANALISE_MENSAL AS (
SELECT 
    YEAR(NF.DATA_VENDA) AS ANO, 
    MONTH(NF.DATA_VENDA) AS MÊS,
	ROUND(SUM([quantidade] * [preco]),2)AS FATURAMENTO_MENSAL,
	ROUND(SUM(SUM([quantidade] * [preco]))OVER (PARTITION BY YEAR(NF.DATA_VENDA)),2) AS FATURAMENTO_ANUAL,
	SUM([quantidade]) AS UNIDADES_VENDIDAS_MES,
	SUM(SUM ([quantidade])) OVER (PARTITION BY YEAR(NF.DATA_VENDA)) AS UNIDADES_VENDIDAS_ANO
FROM 
    [SUCOS_FRUTAS].[dbo].[ITENS_NOTAS_FISCAIS] INF
LEFT JOIN 
    [SUCOS_FRUTAS].[dbo].[NOTAS_FISCAIS] NF ON INF.NUMERO = NF.NUMERO
LEFT JOIN 
    [SUCOS_FRUTAS].[dbo].[TABELA_DE_CLIENTES] C ON NF.CPF = C.CPF
WHERE YEAR(NF.DATA_VENDA) IN (2015,2016,2017)
GROUP BY 
  YEAR(NF.DATA_VENDA), MONTH(NF.DATA_VENDA)  
)
SELECT ANO,
MÊS,
FATURAMENTO_MENSAL,
ROUND(( FATURAMENTO_MENSAL- LAG(FATURAMENTO_MENSAL) OVER (ORDER BY ANO, MÊS)) / LAG(FATURAMENTO_MENSAL) OVER (ORDER BY ANO, MÊS),2) AS  VARIAÇAO_MENSAL_FATURAMENTO,
UNIDADES_VENDIDAS_MES,
(UNIDADES_VENDIDAS_MES - LAG (UNIDADES_VENDIDAS_MES) OVER (ORDER BY ANO, MÊS)) DIFF_MENSAL_UNIDADES_VENDIDAS
FROM ANALISE_MENSAL
ORDER BY ANO, MÊS